// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bridge-redesign/Midnight.tsx": () => import("../components/mockups/bridge-redesign/Midnight.tsx"),
  "./components/mockups/bridge-redesign/Premium.tsx": () => import("../components/mockups/bridge-redesign/Premium.tsx"),
  "./components/mockups/bridge-redesign/Vibrant.tsx": () => import("../components/mockups/bridge-redesign/Vibrant.tsx")
};
